### ISSUE TITLE
wenman按文档使用aop组件出错

### ISSUE THREAD

**Issue by justin-mc-lai** [hyperf/aop-integration#2]
webman的最新版本。

Fatal error: Declaration of Hyperf\AopIntegration\ClassLoader::init(?string $proxyFileDirPath = null, ?string $configDir = null): void must be compatible with Hyperf\Di\ClassLoader::init(?string $proxyFileDirPath = null, ?string $configDir = null, ?Hyperf\Di\ScanHandler\ScanHandlerInterface $handler = null): void in D:\Phpcode\webman-admin\vendor\hyperf\aop-integration\src\ClassLoader.php on line 22

**Comment by limingxinleo** [comment]
嗯，我抽空处理下

**Comment by justin-mc-lai** [comment]
谢谢大佬

**Comment by limingxinleo** [comment]
时隔好几个月，我修复了。。。
